# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: library.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'library.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\"D\n\x06Review\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08reviewer\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0e\n\x06rating\x18\x04 \x01(\x02\"i\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04isbn\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x61uthors\x18\x04 \x03(\t\x12\r\n\x05\x63over\x18\x05 \x01(\t\x12\x18\n\x07reviews\x18\x06 \x03(\x0b\x32\x07.Review\"\x1d\n\x05\x42ooks\x12\x14\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x05.Bookb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REVIEW']._serialized_start=17
  _globals['_REVIEW']._serialized_end=85
  _globals['_BOOK']._serialized_start=87
  _globals['_BOOK']._serialized_end=192
  _globals['_BOOKS']._serialized_start=194
  _globals['_BOOKS']._serialized_end=223
# @@protoc_insertion_point(module_scope)
